import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";
import {  Theme, Container, Box } from "@radix-ui/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Theme
          appearance="light" 
          accentColor="indigo"
          grayColor="gray"
          radius="medium"
          hasBackground={false}
        >
        <Box>
      <Container size={{xl: "3", lg: "3", md: "1", sm: "1", xs: "1"}} >
        {children}
      </Container>
      </Box>
        </Theme>
      </body>
    </html>
  );
}
